NOTAA C
start

1 H PIKAA ADEFHIKLMQRSTVW
2 H PIKAA DE
3 - 5 H PIKAA ADEFHIKLMQRSTVW
6 H PIKAA RK
7 H PIKAA DE
8 - 10 H PIKAA ADEFHIKLMQRSTVW
11 H PIKAA RK
12 H PIKAA DE
13 - 15 H PIKAA ADEFHIKLMQRSTVW
16 H PIKAA RK
17 H PIKAA ADEFHIKLMQRSTVW
